OBJECTS = point.c pixels.c trig.c hopalong_fract.c mandelbrot.c sierpinski.c bifurc.c lorenz.c func.c

build:
	gcc -framework OpenGL -framework GLUT $(OBJECTS) -o point

open: 
	open $(OBJECTS) point.h
